### PR TITLE
Force the user to scroll text to be able to accept the TOS

### PR DESCRIPTION
**Pull request by GretaD**
[Screencast from 16.07.2024 13:58:30.webm](https://github.com/user-attachments/assets/f48ff82e-ebe0-47ba-a465-d1f5ef6adf7f)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> I cannot test it because the modal doesnt show up when i reset it. so just a draft for now

Check the database table oc_termsofservice_sigs. Is it empty after you reset all signatories via the admin settings?

image

The modal shows for me

**Review by ChristophWurst — APPROVED** [review]
Tested & works

**Review by max-nextcloud — COMMENTED** [review]
Looks good to me. I had a look at the code but did not test it yet.

https://github.com/nextcloud/terms_of_service/blob/master/src/Registration.vue#L27-L39 also contains a `ModalContent`. I don't know where the `Registration` component is shown - but I think it will also need to be adjusted as otherwise the `isScrollComplete` will default to false and it will be impossible to submit the TOS.

**Pull request merged**
