### PR TITLE
feat(api): Move from index.php to ocs API 

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Review by GretaD — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
@GretaD or @nickvergessen can we have a bit of documentation?
Mobile team also shall implement it :)

**Comment by nickvergessen** [comment]
we should do openapi I guess.

---

Until then:

So clients should now be able to get the state:
```
GET https://nextcloud31.local/ocs/v2.php/apps/terms_of_service/terms
```
has a data field `"hasSigned":false`
and then they need to open the frontend if possible
or they show the details from that request
and then send a POST to:
```
POST https://nextcloud31.local/ocs/v2.php/apps/terms_of_service/sign
```
should add openapi specs I guess
but at least for the quick fix it should work

**Comment by nickvergessen** [comment]
OpenAPI added in https://github.com/nextcloud/terms_of_service/pull/1011

**Pull request merged**
