### PR TITLE
Fix user_id column length

### LINKED ISSUE #664: ToS can't be activated any more
After click on "aktivieren" the following error occurs:
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.

What I did already:
all common occ db:add-missing* and db:convert 

If it helps:
I reported case #655 and can't activate since then.

Nextcloud Hub II (23.0.0) Ubuntu 20.04.03 LTS with Apache2 2.4.41-4ubuntu3.9

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #664

### CODE REVIEW

**Comment by nickvergessen** [comment]
cc @CI-IT

**Review by vitormattos — APPROVED** [review]

**Pull request merged**
