### PR TITLE
Add SPDX header

### PR DESCRIPTION
**Pull request by AndyScherzinger**
and GH action to check on PRs

### CODE REVIEW

**Review by GretaD — APPROVED** [review]
I dont know how to review this, but Im sure it doesnt break anything :)

**Comment by AndyScherzinger** [comment]
Thanks @GretaD - the only things one could review are:

* Do the added license key words match the former ones in place
* Did generated files get a license header instead of being defined in the dep5 file (else the copyrights will vanish once the file gets re-generated)

**Pull request merged**
