### PR TITLE
fix(officeonline): allow office online wopi requests

### PR DESCRIPTION
**Pull request by max-nextcloud**
Follow up on #765 - also allow the office online app.

### CODE REVIEW

**Comment by max-nextcloud** [comment]
I did not test this myself. Just worked on the code.

**Comment by juliushaertl** [comment]
I can do a test run later this week, but need to get my windows server setup running again.

**Comment by max-nextcloud** [comment]
@juliushaertl I updated the commit message and PR description to reflect that this actually is about office online.

Could you perform the test and then merge ahead?

**Review by juliushaertl — APPROVED** [review]
Tested and works

**Pull request merged**
